### ISSUE TITLE
Is this repo being maintained? 

### ISSUE THREAD

**Issue by m1ch3lp3r3z** [akamai-open/NetStorageKit-PHP#5]
Hi I created a PR https://github.com/akamai-open/NetStorageKit-PHP/pull/4 like a week ago and I was just wondering if it will be considered anytime soon.

Thanks

**Comment by dshafik** [comment]
Hi Michel,

Apologies for not getting to this sooner, I was apparently not signed up for notifications on this repo.

I've merged #4, and plan to spend some time on this library in the near future as [akamai-open/edgegrid-auth](https://github.com/akamai-open/AkamaiOPEN-Edgegrid-php) and [akamai-open/edgegrid-client](https://github.com/akamai-open/AkamaiOPEN-Edgegrid-php-client) libraries reach 1.0.

**Comment by m1ch3lp3r3z** [comment]
Cool, thank you!
